---
title: "Perform a PCA on quantitative data from the pectus cluster project"
output: html_notebook
---

First load up some packages.
```{r}
pacman::p_load(FactoMineR)
```

Get the relevant data.
```{r}
raw_data <- read.csv("C:/Users/csuehs/Documents/00-Projects_Montpellier/PECTUS-Cluster/R_pectus_cluster/pectus_cluster_data.csv")
```

Create a database with the relevant variables.
```{r}
df <- raw_data

df$sex <- NULL
df$pec_fam <- NULL
df$psychosocial <- NULL
df$dyspnea <- NULL
df$palpit <- NULL
df$anom_puls <- NULL

```

Perform PCA.
```{r}
res <- PCA(df[,2:14], scale = TRUE)     ##### Watchout: verify number indices.
```


Get some more info on PCA.
```{r}
summary(res)
```

More plots.
```{r}

pdf(file = "C:/Users/csuehs/Documents/GitHub/pectus_cluster_pca/pectus_cluster_pca_graphics.pdf")

plot(res, choix="ind", axes=c(1,2),cex=1)
plot(res, choix="var", axes=c(1,2), cex=0.5)
plot(res, choix="ind", axes=c(1,3),cex=1)
plot(res, choix="var", axes=c(1,3), cex=0.6)
plot(res, choix="ind", axes=c(2,3),cex=1)
plot(res, choix="var", axes=c(2,3), cex=0.6)

dev.off()
```

